In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from numpy.linalg import inv

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
from sklearn.datasets import load_diabetes
x,y = load_diabetes(return_X_y= True)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y)

In [ ]:
class MultipleRegg:
  def __init__(self):
    self.intercept= 0
    self.coeff= 0
  def fit(self, x_train, y_train):
    x_train= np.insert(x_train, 0,1,axis=1)
    a= inv(np.dot(x_train.T, x_train))
    b= np.dot(x_train.T, y_train)
    beta= a.dot(b)
    #print(beta.shape)
    self.intercept= beta[0]
    self.coeff= beta[1:]
    #print(self.coeff.shape)


  def predict(self, x_test):
    ##x_test= np.insert(x_test, 0 ,1, axis=1)
    y_pred= np.dot(x_test, self.coeff) + self.intercept
    return y_pred
    #print(x_test.shape)

In [ ]:
model = MultipleRegg()

In [ ]:
model.fit(x_train, y_train)

In [ ]:
model.predict(x_test)

array([192.41311399, 163.87620584, 189.49093497, 202.35520696,
       147.11781668, 204.12787333,  97.74309194, 145.9532068 ,
       215.07157381, 104.87888336,  70.90667097, 107.6851459 ,
       155.85658636, 132.40683659, 169.53200372, 118.07533801,
       148.41843448, 214.52212177,  92.75113671,  73.52238582,
        46.68958033,  88.32791156, 146.73183103,  40.33219278,
       193.1691268 , 185.10538832, 180.29266187,  95.46231536,
        56.351874  ,  89.65399592, 154.45629538, 105.90261867,
       200.50061462, 235.71323569, 183.58049033, 141.78154078,
       225.91820897,  95.96477641, 107.99930227, 121.76890427,
       233.88143422, 178.06372574,  75.64594391,  95.74012461,
       299.52589977, 203.70515615,  82.5346309 , 168.60610614,
       160.7576298 , 157.58799581, 102.33222043, 224.54208865,
       125.10392049, 125.75081124, 127.45312298, 119.07264506,
       171.03544207, 208.00509001, 167.44028056,  74.60210901,
       130.37102952, 195.84281936,  61.67289199, 181.63

In [ ]:
model.intercept

152.38771643511743

In [ ]:
model.coeff

array([   8.90849198, -207.48889609,  583.20921819,  329.35886706,
       -673.85103541,  340.58771061,   58.67664129,  136.53072846,
        724.06509974,   18.65537934])

In [ ]:
lr= LinearRegression()

In [ ]:
lr.fit(x_train, y_train)

LinearRegression()

In [ ]:
print(lr.intercept_)
lr.coef_

152.3877164351174


array([   8.90849198, -207.48889609,  583.20921819,  329.35886706,
       -673.85103541,  340.58771061,   58.67664129,  136.53072846,
        724.06509974,   18.65537934])